---
name: Run build job
on:
  workflow_call:
    inputs:
      name:
        required: true
        type: string

jobs:
  build:
    name: Build job ${{ inputs.name }}
    runs-on: self-hosted
    steps:
      - name: Build step 1
        run: echo "step 1"
      - name: Build step 2
        run: echo "step 2"
