---
name: Matrix dispatch
on:
  push

jobs:
  matrix-job:
    name: Third Job
    # runs-on: self-hosted
    strategy:
      max-parallel: 1
      matrix:
        test:
          - name: one
            number: 10
          - name: two
            number: 20
          - name: three
            number: 30
    uses: ./.github/workflows/main.yml
    with:
      name: ${{ matrix.test.name }}
      number: ${{ matrix.test.number }}
