---
name: Run DTS tests
on:
    push:

jobs:
    run-tests:
        name: sleep
        runs-on: self-hosted
        steps:
            - name: sleep
              shell: bash
              run: |
                sleep 10
            - name: echo
              shell: python3 {0}
              run: |
                print(type({}))

    second-job:
        name: Second job
        runs-on: self-hosted
        needs: run-tests
        steps:
            - name: test
              run: |
                echo "test"
