---
name: Run DTS tests
on:
    push:

jobs:
    run-tests:
        name: sleep
        runs-on: self-hosted
        steps:
            - name: sleep
              shell: bash
              run: |
                sleep 10
            - name: echo
              shell: python3 {0}
              run: |
                print("${{ runner.name }}")
            - name: create file
              run: |
                echo "test" > test_file

    second-job:
        name: Second job
        runs-on: self-hosted
        needs: run-tests
        steps:
            - name: test
              run: |
                cat test_file
                echo "${{ runner.name }}"
