---
name: Run DTS tests
on:
    push:

jobs:
    run-tests:
        name: sleep
        runs-on: self-hosted
        outputs:
            RUNNER: ${{ runner.name }}
        steps:
            - name: sleep
              shell: bash
              run: |
                sleep 10
            - name: echo
              shell: python3 {0}
              run: |
                print("${{ runner.name }}")
            - name: create file
              run: |
                echo "test" > test_file

    second-job:
        name: Second job
        runs-on: ${{ needs.run-tests.outputs.RUNNER }}
        needs: run-tests
        steps:
            - name: test
              run: |
                cat test_file
                echo "${{ runner.name }}"

    third-long-job:
        name: Third Job
        runs-on: self-hosted
        strategy:
            matrix:
                var: [1, 2]
        steps:
            - name: wait
              run: |
                sleep 30s
